all: server client

server: server.o
	g++ server.o -o server

client: client.o                                                                                                                g++ client.o -o client

server.o: server.cpp
        g++ -c server.cpp -o server.o 

client.o: client.cpp
	g++ -c client.cpp -o client.o

clean:
	rm *.o server client

